FORMAT: 1A
HOST: https://api.snooker.tools/v1/

# Snooker Stats Api
Snookers Stats is a simple API allowing consumers to record their snooker matches. The api will consume the information and produce statistics.

This api follows the [{json:api}](https://jsonapi.org) specification for all requests and responses.

# Group Users
Group of all users-related resources.

## Users Collection [/users]

### Retrieve a list of users [GET]
Retrieve a list of users the authenticated user is following.

+ Request 

    + Headers 

        Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

	{
		"data": [{
			"type": "user",
			"id": "8c13adcc-9eb9-45d1-8ba7-c0c3789a398b",
			"attributes": {
				"name": "Jon Doe"
			}
		},
		{
			"type": "user",
			"id": "8c13b815-2022-478f-9af3-aed8caa018e3",
			"attributes": {
				"name": "Jane Doe"
			}
		}],
		"links": {
			"self": "https://api.snooker.tools/v1/users"
		}
	}
